# Generated by Django 2.2.12 on 2020-04-21 10:46

from django.db import migrations, models
import recipe.models.models_recipe


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=recipe.models.models_recipe.recipe_image_file_path),
        ),
    ]
